VERSION = '0.3.0'
REFERENCE_FOLDER_ENV = 'INPUT_REFERENCE_FOLDER'
INPUT_BLASTP_ENV = 'INPUT_BLASTP'
INPUT_MIXMHC2PRED_ENV = 'INPUT_MIXMHC2PRED'
INPUT_MIXMHCPRED_ENV = 'INPUT_MIXMHCPRED'
INPUT_RSCRIPT_ENV = 'INPUT_RSCRIPT'
INPUT_NETMHC2PAN_ENV = 'INPUT_NETMHC2PAN'
INPUT_NETMHCPAN_ENV = 'INPUT_NETMHCPAN'

MHC_II = "mhcII"
MHC_I = "mhcI"
