stages:
  - test

test:
  stage: test
  script:
    - apk --no-cache --update-cache add gcc gfortran python3 python3-dev py-pip build-base wget freetype-dev libpng-dev openblas-dev
    - pip3 install --upgrade pip setuptools
    - which python3
    - pip install wheel
    - python3 setup.py bdist_wheel
    - pip install dist/input-0.3.0-py3-none-any.whl
    - python3 -m unittest discover input.tests.input_tests
