stages:
  - test

test:
  stage: test
  script:
    - virtualenv venv
    - source venv/bin/activate
    - python setup.py bdist_wheel
    - pip install dist/input-0.3.0-py3-none-any.whl
    - python -m unittest discover input.tests.input_tests
