image: python:3.7-buster

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    VENV_CACHE_DIR: "$CI_PROJECT_DIR/venv"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - $PIP_CACHE_DIR
    - $VENV_CACHE_DIR

before_script:
  - apt-get update
  - apt-get install gcc gfortran build-essential wget libfreetype6-dev libpng-dev libopenblas-dev
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - test

test:
  stage: test
  script:
    - python setup.py bdist_wheel
    - pip install dist/input-*.whl
    - python -m unittest discover input.tests.unit_tests
