stages:
  - test

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - python setup.py bdist_wheel
    - pip install dist/input-0.3.0-py3-none-any.whl
    - python -m unittest discover input.tests.input_tests
