stages:
  - test

test:
  stage: test
  script:
    - apk add --update python-dev
    - apk add --update py-pip
    - which python
    - python setup.py bdist_wheel
    - pip install dist/input-0.3.0-py3-none-any.whl
    - python -m unittest discover input.tests.input_tests
