VERSION = '0.3.0'
REFERENCE_FOLDER_ENV = 'NEOFOX_REFERENCE_FOLDER'
NEOFOX_BLASTP_ENV = 'NEOFOX_BLASTP'
NEOFOX_MIXMHC2PRED_ENV = 'NEOFOX_MIXMHC2PRED'
NEOFOX_MIXMHCPRED_ENV = 'NEOFOX_MIXMHCPRED'
NEOFOX_RSCRIPT_ENV = 'NEOFOX_RSCRIPT'
NEOFOX_NETMHC2PAN_ENV = 'NEOFOX_NETMHC2PAN'
NEOFOX_NETMHCPAN_ENV = 'NEOFOX_NETMHCPAN'

MHC_II = "mhcII"
MHC_I = "mhcI"
